version: "3.9"

networks:
  us-network:
    driver: bridge
    name: us-network

services:

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    container_name: kong
    image: kong:3.1.1-alpine
    restart: always
    networks:
      - us-network
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 120s
      timeout: 10s
      retries: 3
    volumes:
      - ./compose/kong/declarative:/kong/declarative
      - ./compose/kong/logs:/usr/local/kong/logs
    ports:
      - "8001:8001"
      - "8444:8444"
      - "8000:8000"
      - "8443:8443"
      - "9080:9080"
      - "9081:9081"
  postgres:
    container_name: postgres
    image: postgres:15.1-alpine
    restart: always
    networks:
      - us-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: us
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5